### ISSUE TITLE
Client can only make one request per connection

### ISSUE THREAD

**Issue by Harbinger55555** [ZaykhaKyawSan/RaspberryFileTrans#3]
We may need to account for "multiple files received at an instance" functionality.
(Does this mean a client must not get disconnected after a response or file is received?)

**Comment by Harbinger55555** [comment]
This also leads to another possible bug - if the client requests multiple files, the client parser would not know when to stop exactly while reading from the socket. This means, all the requested files would be combined into one file.

**Comment by ZaykhaKyawSan** [comment]
Fixed.
