### ISSUE TITLE
AES key and IV

### ISSUE THREAD

**Issue by Harbinger55555** [ZaykhaKyawSan/RaspberryFileTrans#7]
It would be desirable to have the AES keys and IVs generated uniquely for each session. This would also mean to find a way to share the generated keys and IVs securely.

**Comment by Mysdreivus** [comment]
Could this be done by using in the encrypt function, IV = Random.new().read(AES.block_size)
Video I was watching used this instead of just a 16 byte text, link => https://www.youtube.com/watch?v=UB2VX4vNUa0

**Comment by Harbinger55555** [comment]
The issue of creating random keys/IVs is that the the AES.py module will be loaded once in server.py and once in client.py. This means that the generated pairs will be different sadly.

**Comment by Mysdreivus** [comment]
Dang, I see what you mean
