### ISSUE TITLE
Some files not decrypted properly

### ISSUE THREAD

**Issue by ZaykhaKyawSan** [ZaykhaKyawSan/RaspberryFileTrans#8]
Files containing the AES padding character are not properly decrypted since the characters will be stripped. This can be solved by using a very rare character as a delimiter. A better but more complicated approach would be to send the length of padding to the decrypt function.

**Comment by Mysdreivus** [comment]
For now we could just use an extremely rare character like you said. This guy in this video https://www.youtube.com/watch?v=UB2VX4vNUa0,

Uses (null) **'\0'** as his padding character.

**Comment by Harbinger55555** [comment]
Unfortunately, it will still have the same issue since we cannot be certain the files being transferred will not contain the character. This issue is evident when transferring image files.

**Comment by Mysdreivus** [comment]
So the only way to fix this is by knowing just how much padding was actually done which would be done by sending the length. So that we don't strip too many characters thus preserving the original state of the file?

**Comment by Harbinger55555** [comment]
That's the only solution I can think up of at the moment. It would mean sending the length first then sending the actual file.

**Comment by Harbinger55555** [comment]
Done.
